version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console:
    format: '%(message)s [%(module)s.%(funcName)s():%(lineno)d]'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: access-daemon.log
    backupCount: 30
    interval: 1
    when: d
root:
  level: DEBUG
  handlers: [console]
loggers:
  himlarcli:
    level: WARNING
  requests:
    level: WARNING
  keystoneclient:
    level: WARNING
#  py.warnings:
#    handlers: [file]
